name: release pipeline demo
 
on:
  push:
    branches: [ "demo" ]
  pull_request:
    branches: [ "demo" ]

jobs:

  job1: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Printing the branch name
      run: echo $GITHUB_REF_NAME    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-app1:$GITHUB_REF_NAME
    - name: LISTING DOCKER IMAGES
      run: docker images